import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '../Shared/NavBar/NavBar.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavBar></NavBar>
        </div>
        {children}
        {/* <FooterBttom></FooterBttom> */}
        </body>
    </html>
  )
}
